version: '2'
services:
    demogit-app:
        image: demogit
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://demogit-mssql:1433;database=jhitest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demogit-mssql:
        extends:
            file: mssql.yml
            service: demogit-mssql
